### ISSUE TITLE
Help file not found

### ISSUE THREAD

**Issue by prdanelli** [ldelossa/nvim-ide#11] opened 2022-11-27 17:42 UTC
I've found a few "issues" while testing and i'm adding them individually so as to keep the discussions focused. 

`:h nvim-ide` doesn't seem to open the help file.

**Comment by mrjones2014** [comment] 2022-11-27 17:50
duplicate of #4

**Comment by ldelossa** [comment] 2022-11-27 18:31
Closing because of Dup, thanks.

**Closed by ldelossa** 2022-11-27 18:31 UTC
